name: Build and Push Cart Service Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t mangesh22898/cart-service:${{ github.sha }} .
        docker push mangesh22898/cart-service:${{ github.sha }}

    - name: Update k8s-manifests repo
      run: |
        git clone https://github.com/mangesh22898/k8s-manifests.git
        cd k8s-manifests/cart
        sed -i "s|image: .*|image: mangesh22898/cart-service:${{ github.sha }}|" deployment.yaml
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git commit -am "Update cart-service image to ${{ github.sha }}"
        git push https://x-access-token:${{ secrets.MANIFEST_REPO_TOKEN }}@github.com/mangesh22898/k8s-manifests.git HEAD:main
